---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: testargo
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: testargo
  labels:
    app: whoami
spec:
  selector:
    app: whoami
  ports:
    - port: 80
      targetPort: 80
